### PR TITLE
Introduces database migration toolchain

### PR DESCRIPTION
**Pull request by funrun11**
* sql-migrate is used
* migration scripts are part of package/docker container
* Example: sql-migrate up -config /etc/platformvisibility/sql-migrate.yml -env="production"
* Docker example: docker run -it --entrypoint=sql-migrate  <image_name> status  --env=production --config /etc/platformvisibility/sql-migrate.yml

---
This change is [Reviewable](https://reviewable.io/reviews/zaletniy/visualization-api/11)

### CODE REVIEW

**Comment by funrun11** [comment]
@oleksiishyman @michaeltillman

**Comment by oleksiishyman** [comment]
do we really have to merge stub migration that creates table?

**Comment by funrun11** [comment]
@oleksiishyman it is executable from deployment point of view and the way how it works it is not going to be changed
It is not stub really, but  just test table :)
Just we have first table from deployment point of view nothing is going to change.

**Comment by oleksiishyman** [comment]
@zaletniy, just to confirm - when we would have our first real table - we would replace 1_test.sql with another file, is it correct?

**Comment by funrun11** [comment]
@oleksiishyman We will create 2_init.sql if it landed already somewhere.
with the first line like `DROP TABLE user;`
If not, replace

**Comment by oleksiishyman** [comment]
No objections from my side, then.

Just to sum it up. Best way to resolve temporary migrations in the future is the following:
1 - create 2_init.sql that would drop tables created in 1_test.sql
2 - all new(real) migrations have to start from timestamp, so user will get understanding what transactions are real, what are fake

**Pull request merged**
